import argparse
from arango_cti_processor.cti_processor import ArangoProcessor
from arango_cti_processor.config import MODE_COLLECTION_MAP


def parse_arguments():
    parser = argparse.ArgumentParser(description="Import STIX JSON into ArangoDB")
    modes = list(MODE_COLLECTION_MAP.keys())
    parser.add_argument(
        "--relationship",
        required=False,
        help=f"you can apply updates to certain collection at run time. Default is all collections. Can select from; {modes}",
        type=lambda x: x.split(","),
        default=modes,
    )

    parser.add_argument(
        "--ignore_embedded_relationships",
        required=False,
        help="This will stop any embedded relationships from being generated.",
    )
    parser.add_argument(
        "--stix2arango_note",
        required=False,
        help=".",
        default="generated by arango_cti_processor",
    )
    parser.add_argument("--database", required=True)
    return parser.parse_args()


def main():
    args = parse_arguments()
    stix_obj = ArangoProcessor(**args.__dict__)
    stix_obj.run()
