import argparse
from .cti_processor import ArangoProcessor

def parse_arguments():
    parser = argparse.ArgumentParser(description="Import STIX JSON into ArangoDB")
    parser.add_argument("--relationship", required=False,
                        help="you can apply updates to certain collection at run time. "
                        "Default is all collections. User can select from; "
                        "mitre_attack_enterprise, mitre_attack_ics, "
                        "mitre_attack_mobile, mitre_capec, nvd_cpe, "
                        "nvd_cve, sigma_rules, disarm")

    parser.add_argument("--ignore_embedded_relationships", required=False,
                        help="This will stop any embedded relationships from being generated.")
    parser.add_argument("--stix2arango_note", required=False,
                        help=".", default="generated by arango_cti_processor")
    parser.add_argument("--arango_database", required=True)
    return parser.parse_args()


def main():
    args = parse_arguments()
    stix_obj = ArangoProcessor(**args.__dict__)
    stix_obj.run()

