import argparse
from arango_cti_processor.cti_processor import ArangoProcessor
from arango_cti_processor.config import MODE_COLLECTION_MAP


def parse_bool(value: str):
    value = value.lower()
    return value in ["yes", "y", "true", "1"]

def parse_arguments():
    parser = argparse.ArgumentParser(description="Import STIX JSON into ArangoDB")
    modes = list(MODE_COLLECTION_MAP.keys())
    parser.add_argument(
        "--relationship",
        required=False,
        help=f"you can apply updates to certain collection at run time. Default is all collections. Can select from; {modes}",
        type=lambda x: x.split(","),
        default=modes,
    )

    parser.add_argument(
        "--ignore_embedded_relationships",
        required=False,
        help="This will stop any embedded relationships from being generated.",
        type=parse_bool,
    )
    parser.add_argument(
        "--stix2arango_note",
        required=False,
        help=".",
        default="generated by arango_cti_processor",
    )
    parser.add_argument(
        "--database",
        required=True,
        help="the arangoDB database name where the objects you want to link are found. It must contain the collections required for the `--relationship` option(s) selected")
    parser.add_argument(
        "--modified_min",
        required=False,
        help="By default arango_cti_processor will consider all objects in the database specified with the property `_is_latest==true` (that is; the latest version of the object). Using this flag with a modified time value will further filter the results processed by arango_cti_processor to STIX objects with a `modified` time >= to the value specified. This is most useful in CVE modes, where a high volume of CVEs are published daily.")
    parser.add_argument(
        "--created_min",
        required=False,
        help="By default arango_cti_processor will consider all objects in the database specified with the property `_is_latest==true` (that is; the latest version of the object). Using this flag with a created time value will further filter the results processed by arango_cti_processor to STIX objects with a `created` time >= to the value specified. This is most useful in CVE modes, where a high volume of CVEs are published daily.")

    return parser.parse_args()


def main():
    args = parse_arguments()
    stix_obj = ArangoProcessor(**args.__dict__)
    stix_obj.run()
